"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");

const firebase = JSON.parse(read("firebase.json"));
const firebaseRc = JSON.parse(read(".firebaserc"));
const storageRules = read("storage.rules");
const firestoreRules = read("firestore.rules");
const firestoreIndexes = JSON.parse(read("firestore.indexes.json"));
const index = read("index.html");
const authSource = read("js/auth.js");
const authCss = read("css/auth.css");
const vectronCss = read("css/vectron.css");
const darkCss = read("css/vectron-dark.css");
const vectronSource = read("js/vectron.js");
const eventSource = read("js/eventHandler.js");
const aamapSource = read("js/aamap.js");
const xmlSource = read("js/xml.js");
const localDraftSource = read("js/localDraft.js");
const functionsSource = read("functions/index.js");

assert.deepStrictEqual(firebase.auth.providers, {emailPassword: true});
assert.deepStrictEqual(firebase.storage, {rules: "storage.rules"});
assert.deepStrictEqual(firebase.firestore, {
    rules: "firestore.rules",
    indexes: "firestore.indexes.json"
});
assert.deepStrictEqual(firebase.functions, {source: "functions", codebase: "default"});
assert.deepStrictEqual(firestoreIndexes, {indexes: [], fieldOverrides: []});
assert.strictEqual(firebaseRc.projects.default, "tronnerrepository");

assert.match(index, /<body class="noscroll auth-locked">/);
assert.match(index, /id="auth-gate"[^>]*aria-modal="true"/);
assert.match(index, /id="auth-login-tab"/);
assert.match(index, /id="auth-signup-tab"/);
assert.match(index, /id="auth-guest"[^>]*auth-guest-button/);
assert.match(index, /Continue as guest/);
assert.match(index, /data-auth-signout/);
assert.match(index, /data-map-upload/);
assert.match(index, /data-map-review-publish/);
assert.match(index, /data-map-repository/);
assert.match(index, /data-notifications/);
assert.match(index, /data-admin-review/);
assert.match(index, /id="notification-overlay"/);
assert.match(index, /id="admin-overlay"/);
assert.match(index, /data-admin-tab="accounts"/);
assert.match(index, /data-admin-tab="submissions"/);
assert.match(index, /data-admin-tab="history"/);
assert.match(index, /data-admin-tab="maps"/);
assert.match(index, /id="map-repository-overlay"[^>]*repository-overlay/);
assert.match(index, /id="map-repository-search"/);
assert.match(index, /id="map-repository-list"/);
assert.match(index, /id="map-repository-mine-tab"[^>]*aria-selected="true"/);
assert.match(index, /id="map-repository-others-tab"[^>]*aria-selected="false"/);
assert.match(index, /id="auth-account-controls"[^>]*auth-account-controls/);
assert.match(index, /id="auth-account-controls"[\s\S]*data-map-upload[\s\S]*data-auth-signout/);
assert.match(index, /class="auth-role-badge" data-auth-role>User<\/span>/);
assert.match(index, /id="top-settings-bar"[\s\S]*id="auth-account-controls"/);
assert.doesNotMatch(index, /class="toolbar-upload"/);
assert.match(index, /id="map_author"[^>]*readonly/);
assert.match(index, /id="map_category"[^>]*value="maps"[^>]*readonly/);
assert.match(index, /id="map_version"[^>]*value="1"[^>]*readonly/);
assert.doesNotMatch(index, /id="map_axes_forced"/);
assert.match(index, /id="map_dtd"[^>]*role="combobox"[^>]*aria-controls="map-dtd-options"/);
assert.strictEqual((index.match(/data-dtd-value=/g) || []).length, 8);
assert.match(index, /id="map-dtd-options"[^>]*role="listbox"/);
assert.match(index, /src="\.\/js\/localDraft\.js"/);
assert.match(index, /<script type="module" src="\.\/js\/auth\.js"><\/script>/);

assert.match(authSource, /projectId:\s*"tronnerrepository"/);
assert.match(authSource, /onAuthStateChanged\(auth/);
assert.match(authSource, /createUserWithEmailAndPassword\(auth/);
assert.match(authSource, /signInWithEmailAndPassword\(auth/);
assert.match(authSource, /sendPasswordResetEmail\(auth/);
assert.match(authSource, /signOut\(auth\)/);
assert.match(authSource, /browserLocalPersistence/);
assert.match(authSource, /browserSessionPersistence/);
assert.match(authSource, /authSdk\.getIdTokenResult\(user, true\)/);
assert.match(authSource, /token\.claims && token\.claims\.admin === true/);
assert.match(authSource, /currentUserRole === "admin"/);
assert.match(authSource, /repositoryMapIsMine\(map\) \|\| currentUserIsAdmin\(\)/);
assert.match(authSource, /firebase-storage\.js/);
assert.match(authSource, /firebase-firestore\.js/);
assert.match(authSource, /uploadString\(mapRef, map\.xml/);
assert.match(authSource, /collection\(firestore, "mapSubmissions"\)/);
assert.match(authSource, /status: "pending"/);
assert.match(authSource, /revisionStoragePath\(user\.uid, submissionRef\.id\)/);
assert.doesNotMatch(authSource, /storageSdk\.listAll/);
assert.doesNotMatch(authSource, /archiveEditedSource/);
assert.doesNotMatch(authSource, /deleteObject\(storageSdk\.ref\(storage, editState\.sourcePath\)\)/);
assert.match(authSource, /if\(auth && auth\.currentUser\)[\s\S]*authSdk\.getIdToken\(auth\.currentUser\)/);
assert.match(authSource, /headers\.Authorization = `Firebase \$\{idToken\}`/);
assert.doesNotMatch(authSource, /getDownloadURL/);
assert.match(authSource, /`\$\{editing \? "Edit" : "Remix"\} \$\{map\.name\} by \$\{map\.author\}`/);
assert.match(authSource, /dataset\.repositoryOpen = map\.fullPath/);
assert.match(authSource, /dataset\.repositoryAction = action/);
assert.match(authSource, /if\(repositoryMapCanEdit\(map\)\) addAction\("edit"\)/);
assert.match(authSource, /if\(!repositoryMapIsMine\(map\) \|\| currentUserIsAdmin\(\)\) addAction\("remix"\)/);
assert.match(authSource, /requestedAction === "edit" && repositoryMapCanEdit\(map\)/);
assert.match(authSource, /repositoryExpandedAuthors = new Set\(\)/);
assert.match(authSource, /heading\.dataset\.repositoryAuthor = author/);
assert.match(authSource, /mapList\.hidden = !expanded/);
assert.match(authSource, /repositoryExpandedAuthors\.clear\(\)/);
assert.match(authSource, /repositoryTab = "mine"/);
assert.match(authSource, /window\.xml_appendRemixSource/);
assert.match(authSource, /depth === 1 \? "_r" : `_r\$\{depth\}`/);
assert.match(authSource, /nameInput\.readOnly = true/);
assert.match(authSource, /function nextAvailableMapVersion\(/);
assert.match(authSource, /reviewing \? "Save review changes"/);
assert.match(authSource, /window\.vectron_getRepositoryEditState/);
assert.match(authSource, /targetAuthor: map\.author/);
assert.match(authSource, /targetAuthorId: map\.authorId/);
assert.match(authSource, /sourceOwnerUid/);
assert.match(authSource, /window\.xml_author = author/);
assert.match(authSource, /window\.xml_category = category/);
assert.match(authSource, /vectron_localDraftSetUser\(draftOwner\)/);
assert.match(authSource, /unlockWorkspace\("guest"\)/);
assert.match(authSource, /function enterGuestMode\(\)/);
assert.match(authSource, /if\(guestMode\)[\s\S]*Sign in or create an account to upload maps/);
assert.match(authSource, /repositoryTab = guestMode \|\| nextTab === "others" \? "others" : "mine"/);
assert.match(authSource, /if\(repositoryMineTab\) repositoryMineTab\.hidden = true/);
assert.match(authSource, /vectron_localDraftSaveNow/);
assert.match(authSource, /setEditorInert\(true\)/);
assert.doesNotMatch(authSource, /[?&](?:skip|bypass|noauth)=/i);
assert.match(authSource, /function ensureAccountRecord\(/);
assert.match(authSource, /function startAccountListener\(/);
assert.match(authSource, /status: "approved"/);
assert.match(authSource, /status: approved \? "approved" : "denied"/);
assert.match(authSource, /function startAdminListeners\(/);
assert.match(authSource, /function reviewAccount\(/);
assert.match(authSource, /function denyRegistration\(/);
assert.match(authSource, /Deny and delete user/);
assert.match(authSource, /REGISTRATION_DENIAL_URL/);
assert.match(authSource, /function reviewSubmission\(/);
assert.match(authSource, /function deleteReviewedMap\(/);
assert.match(authSource, /Deny and delete map/);
assert.match(authSource, /submission\.submissionReason/);
assert.match(authSource, /function buildAdminMapPreview\(/);
assert.match(authSource, /IntersectionObserver/);
assert.match(authSource, /function editPendingSubmission\(/);
assert.match(authSource, /function savePendingReviewDraft\(/);
assert.match(authSource, /publish \? "map\.review\.edit-approve" : "map\.review\.edit"/);
assert.match(authSource, /uploadCurrentMap\(\{publishReview: true\}\)/);
assert.match(authSource, /function renderAdminHistory\(/);
assert.match(authSource, /function reopenReviewHistory\(/);
assert.match(authSource, /action: "map\.review\.reopen"/);
assert.match(authSource, /historySourceSubmissionId: history\.id/);
assert.match(authSource, /actionButton\("Edit map in Vectron", "edit-submission"/);
assert.match(authSource, /operation: "review-edit"/);
assert.match(authSource, /status: publish \? "approved" : "review-draft"/);
assert.match(authSource, /reviewRevisionId: revisionRef\.id/);
assert.match(authSource, /Map approved, published, and returned to server rotation/);
assert.match(authSource, /function editPublishedMapMetadata\(/);
assert.match(authSource, /recipientUid:/);
assert.match(authSource, /collection\(firestore, "auditEvents"\)/);
assert.match(authSource, /Your registration is awaiting admin approval/);
assert.match(authSource, /you cannot submit yet/);

assert.match(vectronSource, /function vectron_start\(\)/);
assert.match(vectronSource, /if\(vectron_started\) return;/);
assert.match(vectronSource, /vectron_localDraftRestore\(\)/);
assert.doesNotMatch(vectronSource, /window\.onload\s*=\s*function\s*\(\)\s*\{\s*vectron_init/);

assert.doesNotMatch(aamapSource + eventSource + xmlSource, /map_axes_forced/);
assert.match(aamapSource, /xml \+= '        <Axes number="'\+axes\+'"\/>'/);
assert.match(eventSource, /mapSettingsCustomCfg\.push\("ARENA_AXES " \+ mapAxes\)/);
assert.match(eventSource, /eventHandler_initDtdCombobox/);
assert.match(xmlSource, /Vectron remix provenance \(oldest source first\)/);
assert.match(xmlSource, /Original map:/);
assert.match(xmlSource, /xml_appendRemixSource/);

assert.match(localDraftSource, /vectron\.localDraft\.v1\./);
assert.match(localDraftSource, /localStorage\.setItem/);
assert.match(localDraftSource, /localStorage\.getItem/);
assert.match(localDraftSource, /beforeunload/);
assert.match(localDraftSource, /visibilitychange/);

assert.match(authCss, /#auth-gate\s*\{[^}]*z-index:\s*20000/s);
assert.match(authCss, /#auth-gate\s*\{[^}]*align-items:\s*center[^}]*justify-items:\s*center/s);
assert.match(authCss, /#auth-gate\s*\{[^}]*background:\s*rgba\(0,\s*0,\s*0,\s*0\.48\)/s);
assert.match(authCss, /\.auth-account-controls\s*\{[^}]*position:\s*static[^}]*margin-left:\s*auto/s);
assert.match(authCss, /\.auth-account-controls\s*\{[^}]*border:\s*0[^}]*background:\s*transparent[^}]*box-shadow:\s*none/s);
assert.match(authCss, /--auth-cyan:\s*#55f4dc/);
assert.match(authCss, /--auth-violet:\s*#9a7cff/);
assert.match(authCss, /\.auth-role-badge\[data-role="admin"\]/);
assert.match(authCss, /\.auth-role-badge\[data-role="guest"\]/);
assert.match(authCss, /\.auth-role-badge\[data-role="pending"\]/);
assert.match(authCss, /\.account-card/);
assert.match(authCss, /\.map-review-card\s*\{[^}]*grid-template-columns:/s);
assert.match(authCss, /\.map-review-actions\s*\{[^}]*flex-direction:\s*column/s);
assert.match(authCss, /\.map-review-preview/);
assert.match(authCss, /\.admin-dialog\s*\{[^}]*resize:\s*both/s);
assert.match(authCss, /\.auth-guest-button/);
assert.doesNotMatch(authCss, /#(?:3b94de|1c70bb|68d6e8|398dcc|1c5f96)/i);
assert.doesNotMatch(index, /auth-backdrop|auth-orbit|auth-horizon/);
assert.match(authCss, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(authCss, /@media \(max-width: 720px\)/);
assert.match(authCss, /\.repository-tabs/);
assert.match(authCss, /button\.repository-author-heading/);
assert.match(authCss, /\.repository-author-heading\[aria-expanded="true"\]/);
assert.match(vectronCss, /\.tsb-combobox-menu/);
assert.match(darkCss, /\.tsb-combobox-menu/);

assert.match(storageRules, /match \/_revisions\/\{ownerUid\}\/\{submissionId\}/);
assert.match(storageRules, /allow get: if canReadRevision\(ownerUid, submissionId\)/);
assert.match(storageRules, /submission\(submissionId\)\.data\.status == 'approved'/);
assert.match(storageRules, /request\.auth\.uid == ownerUid/);
assert.match(storageRules, /account\(request\.auth\.uid\)\.data\.status == 'approved'/);
assert.match(storageRules, /request\.resource\.metadata\.submissionId == submissionId/);
assert.match(storageRules, /request\.resource\.metadata\.mapVersion\.matches\('\(v\|V\)\?\[0-9\]\+/);
assert.match(storageRules, /author != '_revisions'/);
assert.match(storageRules, /fileName\.matches\('\.\*\\\\\.aamap\\\\\.xml'\)/);
assert.match(storageRules, /request\.auth\.token\.admin == true/);
assert.match(authSource, /editorUid: user\.uid/);
assert.match(authSource, /editorRole: currentUserRole/);
assert.match(storageRules, /allow update: if false/);
assert.doesNotMatch(storageRules, /allow (?:read|write): if true/);
assert.doesNotMatch(storageRules, /allow (?:create|delete|write): if true/);

assert.match(firestoreRules, /match \/accounts\/\{uid\}/);
assert.match(firestoreRules, /request\.resource\.data\.status == 'pending'/);
assert.match(firestoreRules, /match \/maps\/\{mapId\}/);
assert.match(firestoreRules, /resource\.data\.status == 'active' \|\| isAdmin\(\)/);
assert.match(firestoreRules, /match \/resourcePaths\/\{resourceId\}/);
assert.match(firestoreRules, /allow create: if isAdmin\(\) \|\| \(hasApprovedAccount\(\)/);
assert.match(firestoreRules, /match \/mapSubmissions\/\{submissionId\}/);
assert.match(firestoreRules, /match \/notifications\/\{uid\}\/items\/\{notificationId\}/);
assert.match(firestoreRules, /affectedKeys\(\)\.hasOnly\(\['readAt'\]\)/);
assert.match(firestoreRules, /match \/auditEvents\/\{eventId\}/);
assert.doesNotMatch(firestoreRules, /allow write: if true/);

assert.match(functionsSource, /exports\.denyRegistration = onRequest/);
assert.match(functionsSource, /verifyIdToken\(match\[1\], true\)/);
assert.match(functionsSource, /token\.admin !== true/);
assert.match(functionsSource, /adminAuth\.deleteUser\(accountId\)/);
assert.match(functionsSource, /action: "account\.deny-delete"/);

console.log("Vectron authentication configuration tests passed.");
