"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");

const firebase = JSON.parse(read("firebase.json"));
const firebaseRc = JSON.parse(read(".firebaserc"));
const storageRules = read("storage.rules");
const firestoreRules = read("firestore.rules");
const firestoreIndexes = JSON.parse(read("firestore.indexes.json"));
const index = read("index.html");
const authSource = read("js/auth.js");
const authCss = read("css/auth.css");
const vectronCss = read("css/vectron.css");
const darkCss = read("css/vectron-dark.css");
const vectronSource = read("js/vectron.js");
const eventSource = read("js/eventHandler.js");
const aamapSource = read("js/aamap.js");
const selectSource = read("js/AamapTools/selectTool.js");
const editSelectedSource = read("js/AamapTools/editSelectedTool.js");
const zoneSource = read("js/AamapObjects/Zone.js");
const xmlSource = read("js/xml.js");
const localDraftSource = read("js/localDraft.js");
const functionsSource = read("functions/index.js");

assert.deepStrictEqual(firebase.auth.providers, {emailPassword: true});
assert.deepStrictEqual(firebase.storage, {rules: "storage.rules"});
assert.deepStrictEqual(firebase.firestore, {
    rules: "firestore.rules",
    indexes: "firestore.indexes.json"
});
assert.deepStrictEqual(firebase.functions, {source: "functions", codebase: "default"});
assert.deepStrictEqual(firestoreIndexes, {indexes: [], fieldOverrides: []});
assert.strictEqual(firebaseRc.projects.default, "tronnerrepository");

assert.match(index, /<body class="noscroll auth-locked">/);
assert.match(index, /id="auth-gate"[^>]*aria-modal="true"/);
assert.match(index, /id="auth-login-tab"/);
assert.match(index, /id="auth-signup-tab"/);
assert.match(index, /id="auth-guest"[^>]*auth-guest-button/);
assert.match(index, /Continue as guest/);
assert.match(index, /data-auth-signout/);
assert.match(index, /data-map-upload/);
assert.match(index, /data-map-review-publish/);
assert.match(index, /data-map-review-publish[^>]*title="Approve"[^>]*aria-label="Approve"[\s\S]*?<span>Approve<\/span>/);
assert.match(index, /data-map-review-deny[^>]*title="Deny"[^>]*aria-label="Deny"[\s\S]*?<span>Deny<\/span>/);
assert.match(index, /data-map-review-deny[\s\S]*data-map-review-publish/);
assert.match(index, /data-map-repository/);
assert.match(index, /data-notifications/);
assert.match(index, /data-admin-review/);
assert.match(index, /id="notification-overlay"/);
assert.match(index, /id="admin-overlay"/);
assert.match(index, /id="map-file-command-overlay"/);
assert.match(index, /id="map-file-command-value"[^>]*readonly/);
assert.match(index, /id="map-file-command-copy"/);
assert.match(index, /id="auth-confirm-popover"[^>]*role="dialog"/);
assert.match(index, /id="auth-confirm-reason"[^>]*type="text"[^>]*maxlength="1000"/);
assert.doesNotMatch(index, /<textarea id="auth-confirm-reason"/);
assert.match(index, /id="auth-confirm-reason-error"[^>]*role="alert"/);
assert.match(index, /id="auth-confirm-quick-reasons"[^>]*role="group"[^>]*aria-label="Quick denial reasons"/);
assert.match(index, /data-admin-tab="accounts"/);
assert.match(index, /data-admin-tab="submissions"/);
assert.match(index, /data-admin-tab="history"/);
assert.match(index, /data-admin-tab="maps"/);
assert.match(index, /id="map-repository-overlay"[^>]*repository-overlay/);
assert.match(index, /id="map-repository-search"/);
assert.match(index, /id="map-repository-list"/);
assert.match(index, /id="map-repository-mine-tab"[^>]*aria-selected="true"/);
assert.match(index, /id="map-repository-others-tab"[^>]*aria-selected="false"/);
assert.match(index, /id="auth-account-controls"[^>]*auth-account-controls/);
assert.match(index, /id="auth-account-controls"[\s\S]*data-map-upload[\s\S]*data-auth-signout/);
assert.match(index, /class="auth-role-badge" data-auth-role>User<\/span>/);
assert.match(index, /id="top-settings-bar"[\s\S]*id="auth-account-controls"/);
assert.doesNotMatch(index, /class="toolbar-upload"/);
assert.match(index, /id="map_author"[^>]*readonly/);
assert.match(index, /id="map_category"[^>]*value="maps"[^>]*readonly/);
assert.match(index, /id="map_version"[^>]*value="1"[^>]*readonly/);
assert.doesNotMatch(index, /id="map_axes_forced"/);
assert.match(index, /id="map_dtd"[^>]*role="combobox"[^>]*aria-controls="map-dtd-options"/);
assert.strictEqual((index.match(/data-dtd-value=/g) || []).length, 8);
assert.match(index, /id="map-dtd-options"[^>]*role="listbox"/);
assert.match(index, /src="\.\/js\/localDraft\.js"/);
assert.match(index, /src="\.\/js\/AamapTools\/editSelectedTool\.js"/);
assert.match(index, /id="edit-selected-window"/);
assert.match(index, /id="contextMenu-edit-selected"/);
assert.match(index, /<script type="module" src="\.\/js\/auth\.js"><\/script>/);

assert.match(authSource, /projectId:\s*"tronnerrepository"/);
assert.match(authSource, /onAuthStateChanged\(auth/);
assert.match(authSource, /createUserWithEmailAndPassword\(auth/);
assert.match(authSource, /signInWithEmailAndPassword\(auth/);
assert.match(authSource, /sendPasswordResetEmail\(auth/);
assert.match(authSource, /signOut\(auth\)/);
assert.match(authSource, /browserLocalPersistence/);
assert.match(authSource, /browserSessionPersistence/);
assert.match(authSource, /authSdk\.getIdTokenResult\(user, true\)/);
assert.match(authSource, /token\.claims && token\.claims\.admin === true/);
assert.match(authSource, /currentUserRole === "admin"/);
assert.match(authSource, /repositoryMapIsMine\(map\) \|\| currentUserIsAdmin\(\)/);
assert.match(authSource, /firebase-storage\.js/);
assert.match(authSource, /firebase-firestore\.js/);
assert.match(authSource, /uploadString\(mapRef, map\.xml/);
assert.match(authSource, /collection\(firestore, "mapSubmissions"\)/);
assert.match(authSource, /status: "pending"/);
assert.match(authSource, /revisionStoragePath\(\s*user\.uid, submissionRef\.id,/);
assert.match(authSource, /const category = MAP_CATEGORY;/);
assert.match(authSource, /const finalCategory = target\.category;/);
assert.match(authSource, /category\.value = MAP_CATEGORY;[\s\S]*category\.readOnly = true;/);
assert.match(authSource, /function showMapFileCommand\(/);
assert.match(authSource, /mapFileCommand\([\s\S]*FIREBASE_CONFIG\.storageBucket/);
assert.match(authSource, /showMapFileCommand\(mapName, mapVersion, objectPath\)/);
assert.doesNotMatch(authSource, /storageSdk\.listAll/);
assert.doesNotMatch(authSource, /archiveEditedSource/);
assert.doesNotMatch(authSource, /deleteObject\(storageSdk\.ref\(storage, editState\.sourcePath\)\)/);
assert.match(authSource, /if\(auth && auth\.currentUser\)[\s\S]*authSdk\.getIdToken\(auth\.currentUser\)/);
assert.match(authSource, /headers\.Authorization = `Firebase \$\{idToken\}`/);
assert.doesNotMatch(authSource, /getDownloadURL/);
assert.match(storageRules, /request\.resource\.metadata\.category == 'maps'/);
assert.match(authSource, /MAP_SUBMISSION_URL = .*createMapSubmission/);
assert.match(authSource, /function nextAvailableSubmissionVersion\(/);
assert.match(authSource, /"pendingResourcePaths", resourceId/);
assert.match(authSource, /legacyPending/);
assert.match(authSource, /version = bumpMapVersion\(version\)/);
assert.match(authSource, /async function createMapSubmission\(/);
assert.match(authSource, /await createMapSubmission\(user,/);
assert.doesNotMatch(authSource, /await firestoreSdk\.setDoc\(submissionRef,/);
assert.match(authSource, /pendingResourceSnapshot\.data\(\)\.submissionId === submissionId/);
assert.match(authSource, /transaction\.delete\(pendingResourceRef\)/);
assert.match(authSource, /pendingResourceId: publish \? "" : finalPendingResourceId/);
assert.match(authSource, /transaction\.set\(finalPendingRef,/);
assert.match(authSource, /let repositorySubmissions = \[\]/);
assert.match(authSource, /where\("submittedBy", "==", auth\.currentUser\.uid\)/);
assert.match(authSource, /item\.data\(\)\.status === "denied"/);
assert.match(authSource, /"edit-denied"/);
assert.match(authSource, /deniedSubmissionId: map\.denied \? map\.submissionId : ""/);
assert.match(authSource, /resubmissionOf,/);
assert.match(authSource, /Edited and resubmitted after a denied review/);
assert.match(authSource, /dataset\.repositoryOpen = map\.fullPath/);
assert.match(authSource, /dataset\.repositoryAction = action/);
assert.match(authSource, /addAction\(map\.denied \? "edit-denied" : "edit"\)/);
assert.match(authSource, /if\(!map\.denied && \(!repositoryMapIsMine\(map\) \|\| currentUserIsAdmin\(\)\)\) addAction\("remix"\)/);
assert.match(authSource, /\["edit", "edit-denied"\]\.includes\(requestedAction\)/);
assert.match(authSource, /repositoryExpandedAuthors = new Set\(\)/);
assert.match(authSource, /heading\.dataset\.repositoryAuthor = author/);
assert.match(authSource, /mapList\.hidden = !expanded/);
assert.match(authSource, /repositoryExpandedAuthors\.clear\(\)/);
assert.match(authSource, /repositoryTab = "mine"/);
assert.match(authSource, /window\.xml_appendRemixSource/);
assert.match(authSource, /depth === 1 \? "_r" : `_r\$\{depth\}`/);
assert.match(authSource, /nameInput\.readOnly = true/);
assert.match(authSource, /function nextAvailableMapVersion\(/);
assert.match(authSource, /reviewing \? "Save review changes"/);
assert.match(authSource, /window\.vectron_getRepositoryEditState/);
assert.match(authSource, /targetAuthor: map\.author/);
assert.match(authSource, /targetAuthorId: map\.authorId/);
assert.match(authSource, /sourceOwnerUid/);
assert.match(authSource, /window\.xml_author = author/);
assert.match(authSource, /window\.xml_category = category/);
assert.match(authSource, /authorInput\.readOnly = !admin/);
assert.match(authSource, /versionInput\.readOnly = !admin/);
assert.match(authSource, /if\(lockedName && !admin\)/);
assert.match(authSource, /function uploadAuthorIdentity\(/);
assert.match(authSource, /vectron_localDraftSetUser\(draftOwner\)/);
assert.match(authSource, /unlockWorkspace\("guest"\)/);
assert.match(authSource, /function enterGuestMode\(\)/);
assert.match(authSource, /if\(guestMode\)[\s\S]*Sign in or create an account to upload maps/);
assert.match(authSource, /repositoryTab = guestMode \|\| nextTab === "others" \? "others" : "mine"/);
assert.match(authSource, /if\(repositoryMineTab\) repositoryMineTab\.hidden = true/);
assert.match(authSource, /vectron_localDraftSaveNow/);
assert.match(authSource, /setEditorInert\(true\)/);
assert.doesNotMatch(authSource, /[?&](?:skip|bypass|noauth)=/i);
assert.match(authSource, /function ensureAccountRecord\(/);
assert.match(authSource, /function startAccountListener\(/);
assert.match(authSource, /status: "approved"/);
assert.match(authSource, /status: approved \? "approved" : "denied"/);
assert.match(authSource, /function startAdminListeners\(/);
assert.match(authSource, /function reviewAccount\(/);
assert.match(authSource, /function denyRegistration\(/);
assert.match(authSource, /Deny and delete user/);
assert.match(authSource, /REGISTRATION_DENIAL_URL/);
assert.match(authSource, /function reviewSubmission\(/);
assert.match(authSource, /function denyCurrentReview\(/);
assert.match(authSource, /reasonRequired:true/);
assert.match(authSource, /QUICK_DENY_REASONS = Object\.freeze\(\[[\s\S]*"Tunnel Trouble"[\s\S]*"Too Easy"[\s\S]*"Too Long"[\s\S]*"Not a Race Map"[\s\S]*"duplicate"/);
assert.match(authSource, /function populateQuickDenyReasons\(/);
assert.match(authSource, /CUSTOM_QUICK_DENY_REASONS_KEY = "vectron\.quickDenyReasons\.v1"/);
assert.match(authSource, /window\.localStorage\.getItem\(CUSTOM_QUICK_DENY_REASONS_KEY\)/);
assert.match(authSource, /window\.localStorage\.setItem\([\s\S]*CUSTOM_QUICK_DENY_REASONS_KEY/);
assert.match(authSource, /function addCustomQuickDenyReason\(/);
assert.match(authSource, /function removeCustomQuickDenyReason\(/);
assert.match(authSource, /dataset\.denyQuickAdd/);
assert.match(authSource, /dataset\.denyQuickRemove/);
assert.match(authSource, /reason\.type = "text"/);
assert.match(authSource, /submitAdminSubmissionDenial\(submission\.id, reason\)/);
assert.match(authSource, /function submitAdminSubmissionDenial\([\s\S]*skipConfirmation:true/);
assert.match(authSource, /confirmReasonInput\.addEventListener\("keydown"[\s\S]*event\.key !== "Enter"[\s\S]*settleConfirmation\(true\)/);
assert.match(authSource, /reviewSubmission\(editState\.reviewSubmissionId, false, \{[\s\S]*skipConfirmation:true/);
assert.match(authSource, /reviewDenyButton\.addEventListener\("click"/);
assert.match(authSource, /function adminMapIdentity\(/);
assert.match(authSource, /data-admin-map-author/);
assert.match(authSource, /data-admin-map-name/);
assert.match(authSource, /data-admin-map-version/);
assert.match(authSource, /function nextAvailableAdminVersion\(/);
assert.match(authSource, /target\.mapName !== submission\.mapName/);
assert.match(authSource, /name: target\.mapName/);
assert.match(authSource, /version: target\.mapVersion/);
assert.match(authSource, /A pending create may have[\s\S]*become an edit/);
assert.match(authSource, /function deleteReviewedMap\(/);
assert.match(authSource, /Deny and delete map/);
assert.match(authSource, /submission\.submissionReason/);
assert.match(authSource, /function buildAdminMapPreview\(/);
assert.match(authSource, /map-preview-checkpoint-label/);
assert.match(authSource, /map-preview-teleport-link/);
assert.match(authSource, /IntersectionObserver/);
assert.match(authSource, /function editPendingSubmission\(/);
assert.match(authSource, /function pendingSubmissionIdentity[\s\S]*nextAvailableAdminVersion\(/);
assert.match(authSource, /function loadPendingSubmissionIntoEditor\(/);
assert.match(authSource, /function nextPendingSubmissionAfter\(/);
assert.match(authSource, /nextPendingSubmissionAfter\(editState\.reviewSubmissionId\)/);
assert.match(authSource, /const nextSubmission = nextPendingSubmissionAfter\(editState\.reviewSubmissionId\)/);
assert.match(authSource, /Now editing [\s\S]*the next map in the review queue/);
assert.match(authSource, /The map review queue is clear/);
assert.match(authSource, /if\(publish\)[\s\S]*nextPendingSubmissionAfter[\s\S]*} else \{[\s\S]*showMapFileCommand\(mapName, mapVersion, objectPath\)/);
assert.match(authSource, /confirmLabel:"Approve"/);
assert.match(authSource, /function nextAvailableReviewVersion[\s\S]*let version = normalizeMapVersion\(startingVersion\)/);
assert.match(authSource, /function savePendingReviewDraft\(/);
assert.match(authSource, /publish \? "map\.review\.edit-approve" : "map\.review\.edit"/);
assert.match(authSource, /uploadCurrentMap\(\{publishReview: true\}\)/);
assert.match(authSource, /function renderAdminHistory\(/);
assert.match(authSource, /function renderAdminMap\([\s\S]*map-review-published-card/);
assert.match(authSource, /dataset\.adminPreviewId = `published:\$\{map\.id\}`/);
assert.match(authSource, /queueAdminSubmissionPreview\(preview, map\)/);
assert.match(authSource, /function reopenReviewHistory\(/);
assert.match(authSource, /action: "map\.review\.reopen"/);
assert.match(authSource, /historySourceSubmissionId: history\.id/);
assert.match(authSource, /actionButton\("Edit map in Vectron", "edit-submission"/);
assert.match(authSource, /operation: "review-edit"/);
assert.match(authSource, /status: publish \? "approved" : "review-draft"/);
assert.match(authSource, /reviewRevisionId: revisionRef\.id/);
assert.match(authSource, /Map approved, published, and returned to server rotation/);
assert.match(authSource, /function editPublishedMapMetadata\(/);
assert.match(authSource, /recipientUid:/);
assert.match(authSource, /collection\(firestore, "auditEvents"\)/);
assert.match(authSource, /Your registration is awaiting admin approval/);
assert.match(authSource, /you cannot submit yet/);
assert.match(authSource, /function confirmAction\(/);
assert.match(authSource, /function anchorAdminDialog\(/);
assert.match(authSource, /adminDialog\.classList\.add\("positioned"\)/);
assert.match(authSource, /function setAdminTab[\s\S]*adminList\.scrollTop = 0;[\s\S]*renderAdminList\(\)/);
assert.match(authSource, /function refreshAdminQueues[\s\S]*adminList\.scrollTop = 0;[\s\S]*startAdminListeners\(\)/);
assert.match(authSource, /function setRepositoryTab[\s\S]*repositoryList\.scrollTop = 0;[\s\S]*renderRepositoryMaps\(\)/);
assert.match(authSource, /function refreshRepositoryMaps[\s\S]*repositoryList\.scrollTop = 0;/);
assert.match(authSource, /adminRefreshButton\.addEventListener\("click", refreshAdminQueues\)/);
assert.doesNotMatch(authSource, /window\.(?:confirm|alert)\s*\(/);

const nextSubmissionSource = authSource.match(
    /function nextPendingSubmissionAfter\(submissionId\) \{[\s\S]*?\n\}/
);
assert.ok(nextSubmissionSource, "The next-review selector must remain independently testable");
const nextSubmissionContext = {
    adminData: {submissions: [{id:"first"}, {id:"second"}, {id:"third"}]},
    selected: null
};
vm.runInNewContext(
    `${nextSubmissionSource[0]}\nselected = nextPendingSubmissionAfter("second");`,
    nextSubmissionContext
);
assert.strictEqual(nextSubmissionContext.selected.id, "third",
    "Approval advances to the following queued map");
vm.runInNewContext(
    `${nextSubmissionSource[0]}\nselected = nextPendingSubmissionAfter("third");`,
    nextSubmissionContext
);
assert.strictEqual(nextSubmissionContext.selected.id, "first",
    "Approval wraps to the first remaining queued map");
nextSubmissionContext.adminData.submissions = [{id:"only"}];
vm.runInNewContext(
    `${nextSubmissionSource[0]}\nselected = nextPendingSubmissionAfter("only");`,
    nextSubmissionContext
);
assert.strictEqual(nextSubmissionContext.selected, null,
    "Approval leaves the editor idle when the review queue is clear");

assert.match(vectronSource, /function vectron_start\(\)/);
assert.match(vectronSource, /if\(vectron_started\) return;/);
assert.match(vectronSource, /vectron_localDraftRestore\(\)/);
assert.doesNotMatch(vectronSource, /window\.onload\s*=\s*function\s*\(\)\s*\{\s*vectron_init/);

assert.doesNotMatch(aamapSource + eventSource + xmlSource, /map_axes_forced/);
assert.match(aamapSource, /xml \+= '        <Axes number="'\+axes\+'"\/>'/);
assert.match(eventSource, /mapSettingsCustomCfg\.push\("ARENA_AXES " \+ mapAxes\)/);
assert.match(eventSource, /eventHandler_initDtdCombobox/);
assert.match(xmlSource, /Vectron remix provenance \(oldest source first\)/);
assert.match(xmlSource, /Original map:/);
assert.match(xmlSource, /xml_appendRemixSource/);

assert.match(localDraftSource, /vectron\.localDraft\.v1\./);
assert.match(localDraftSource, /localStorage\.setItem/);
assert.match(localDraftSource, /localStorage\.getItem/);
assert.match(localDraftSource, /beforeunload/);
assert.match(localDraftSource, /visibilitychange/);

assert.match(authCss, /#auth-gate\s*\{[^}]*z-index:\s*20000/s);
assert.match(authCss, /#auth-gate\s*\{[^}]*align-items:\s*center[^}]*justify-items:\s*center/s);
assert.match(authCss, /#auth-gate\s*\{[^}]*background:\s*rgba\(0,\s*0,\s*0,\s*0\.48\)/s);
assert.match(authCss, /\.auth-account-controls\s*\{[^}]*position:\s*static[^}]*margin-left:\s*auto/s);
assert.match(authCss, /\.auth-account-controls\s*\{[^}]*border:\s*0[^}]*background:\s*transparent[^}]*box-shadow:\s*none/s);
assert.match(authCss, /--auth-cyan:\s*#55f4dc/);
assert.match(authCss, /--auth-violet:\s*#9a7cff/);
assert.match(authCss, /\.auth-role-badge\[data-role="admin"\]/);
assert.match(authCss, /\.auth-role-badge\[data-role="guest"\]/);
assert.match(authCss, /\.auth-role-badge\[data-role="pending"\]/);
assert.match(authCss, /\.account-card/);
assert.match(authCss, /\.map-review-card\s*\{[^}]*grid-template-columns:/s);
assert.match(authCss, /\.map-review-actions\s*\{[^}]*flex-direction:\s*column/s);
assert.match(authCss, /\.map-review-preview/);
assert.match(authCss, /\.admin-dialog\s*\{[^}]*resize:\s*both/s);
assert.match(authCss, /\.admin-dialog\s*\{[^}]*width:\s*min\(620px, 100%\)/s);
assert.match(authCss, /\.admin-dialog\s*\{[^}]*height:\s*calc\(100vh - 48px\)/s);
assert.match(authCss, /\.map-file-command-dialog\s*\{/);
assert.match(authCss, /\.admin-dialog\.positioned\s*\{[^}]*position:\s*fixed/s);
assert.match(authCss, /\.admin-dialog \.repository-header\s*\{[^}]*cursor:\s*move/s);
assert.match(authCss, /\.auth-confirm-popover/);
assert.match(authCss, /\.auth-review-deny-button/);
assert.match(authCss, /\.auth-confirm-reason-field input/);
assert.match(authCss, /\.auth-deny-quick-reasons/);
assert.match(authCss, /\.account-card-button\.auth-deny-quick-reason/);
assert.match(authCss, /\.auth-deny-quick-custom/);
assert.match(authCss, /\.auth-deny-quick-remove/);
assert.match(authCss, /\.account-card-button\.auth-deny-quick-add/);
assert.match(authCss, /\.map-preview-checkpoint-label/);
assert.match(authCss, /\.map-preview-teleport-link/);
assert.match(authCss, /\.auth-guest-button/);
assert.doesNotMatch(authCss, /#(?:3b94de|1c70bb|68d6e8|398dcc|1c5f96)/i);
assert.doesNotMatch(index, /auth-backdrop|auth-orbit|auth-horizon/);
assert.match(authCss, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(authCss, /@media \(max-width: 720px\)/);
assert.match(authCss, /\.repository-tabs/);
assert.match(authCss, /button\.repository-author-heading/);
assert.match(authCss, /\.repository-author-heading\[aria-expanded="true"\]/);
assert.match(vectronCss, /\.tsb-combobox-menu/);
assert.match(vectronCss, /#wall-tool-window\s*\{[^}]*height:\s*fit-content/s);
assert.match(vectronCss, /#zone-tool-window\s*\{[^}]*height:\s*fit-content/s);
assert.match(vectronCss, /#edit-selected-window\s*\{[^}]*height:\s*fit-content/s);
assert.match(read("js/gui.js"), /defaultHeight:\s*"auto"/);
assert.match(darkCss, /\.tsb-combobox-menu/);
assert.match(darkCss, /#edit-selected-window/);
assert.match(editSelectedSource, /function editSelected_applyWalls\(/);
assert.match(editSelectedSource, /function editSelected_applyZones\(/);
assert.match(editSelectedSource, /function editSelected_applySpawns\(/);
assert.match(selectSource, /function selectTool_findTeleportDestinationAt\(/);
assert.match(selectSource, /label:"Move teleport destination"/);
assert.match(zoneSource, /function\(x, y\)[\s\S]*this\.setTeleportDestination/);
assert.match(eventSource, /if\(e\.which === 3 \|\| e\.button === 2\) return;/);

assert.match(storageRules, /match \/_revisions\/\{ownerUid\}\/\{submissionId\}/);
assert.match(storageRules, /match \/_revisions\/\{ownerUid\}\/\{submissionId\}\/\{fileName\}/);
assert.match(storageRules, /canReadRevision\(ownerUid, submissionId, expectedPath\)/);
assert.match(storageRules, /submission\(submissionId\)\.data\.storagePath == expectedPath/);
assert.match(storageRules, /request\.auth\.uid == ownerUid/);
assert.match(storageRules, /account\(request\.auth\.uid\)\.data\.status == 'approved'/);
assert.match(storageRules, /request\.resource\.metadata\.submissionId == submissionId/);
assert.doesNotMatch(storageRules, /metadata\.mapVersion\.matches/);
assert.match(storageRules, /request\.resource\.metadata\.mapVersion\.size\(\) > 0/);
assert.match(storageRules, /author != '_revisions'/);
assert.match(storageRules, /fileName\.matches\('\.\*\\\\\.aamap\\\\\.xml'\)/);
assert.match(storageRules, /request\.auth\.token\.admin == true/);
assert.match(authSource, /editorUid: user\.uid/);
assert.match(authSource, /editorRole: currentUserRole/);
assert.match(storageRules, /allow update: if false/);
assert.doesNotMatch(storageRules, /allow (?:read|write): if true/);
assert.doesNotMatch(storageRules, /allow (?:create|delete|write): if true/);

assert.match(firestoreRules, /match \/accounts\/\{uid\}/);
assert.match(firestoreRules, /request\.resource\.data\.status == 'pending'/);
assert.match(firestoreRules, /match \/maps\/\{mapId\}/);
assert.match(firestoreRules, /resource\.data\.status == 'active' \|\| isAdmin\(\)/);
assert.match(firestoreRules, /match \/resourcePaths\/\{resourceId\}/);
assert.match(firestoreRules, /match \/pendingResourcePaths\/\{resourceId\}/);
assert.match(firestoreRules, /match \/pendingResourcePaths\/\{resourceId\}[\s\S]*allow read: if signedIn\(\)/);
assert.match(firestoreRules, /match \/mapSubmissions\/\{submissionId\}/);
assert.match(firestoreRules, /match \/mapSubmissions\/\{submissionId\}[\s\S]*allow create: if isAdmin\(\)/);
assert.match(firestoreRules, /match \/notifications\/\{uid\}\/items\/\{notificationId\}/);
assert.match(firestoreRules, /affectedKeys\(\)\.hasOnly\(\['readAt'\]\)/);
assert.match(firestoreRules, /match \/auditEvents\/\{eventId\}/);
assert.doesNotMatch(firestoreRules, /allow write: if true/);

assert.match(functionsSource, /exports\.denyRegistration = onRequest/);
assert.match(functionsSource, /exports\.createMapSubmission = onRequest/);
assert.match(functionsSource, /function mapFileName\(/);
assert.match(functionsSource, /const admin = user\.admin === true/);
assert.match(functionsSource, /if\(!admin && \(payload\.authorId !== account\.authorId/);
assert.match(functionsSource, /duplicatePendingSubmission\(authorSubmissions, payload\)/);
assert.match(functionsSource, /transaction\.get\(resourceRef\)/);
assert.match(functionsSource, /transaction\.get\(pendingRef\)/);
assert.match(functionsSource, /transaction\.create\(submissionRef/);
assert.match(functionsSource, /transaction\.create\(pendingRef/);
assert.match(functionsSource, /denied\.status !== "denied"/);
assert.match(functionsSource, /custom\.sha256 !== payload\.sha256/);
assert.match(functionsSource, /verifyIdToken\(match\[1\], true\)/);
assert.match(functionsSource, /token\.admin !== true/);
assert.match(functionsSource, /adminAuth\.deleteUser\(accountId\)/);
assert.match(functionsSource, /action: "account\.deny-delete"/);

console.log("Vectron authentication configuration tests passed.");
