"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");

const firebase = JSON.parse(read("firebase.json"));
const firebaseRc = JSON.parse(read(".firebaserc"));
const storageRules = read("storage.rules");
const index = read("index.html");
const authSource = read("js/auth.js");
const authCss = read("css/auth.css");
const vectronCss = read("css/vectron.css");
const darkCss = read("css/vectron-dark.css");
const vectronSource = read("js/vectron.js");
const eventSource = read("js/eventHandler.js");
const aamapSource = read("js/aamap.js");
const xmlSource = read("js/xml.js");
const localDraftSource = read("js/localDraft.js");

assert.deepStrictEqual(firebase.auth.providers, {emailPassword: true});
assert.deepStrictEqual(firebase.storage, {rules: "storage.rules"});
assert.strictEqual(firebaseRc.projects.default, "tronnerrepository");

assert.match(index, /<body class="noscroll auth-locked">/);
assert.match(index, /id="auth-gate"[^>]*aria-modal="true"/);
assert.match(index, /id="auth-login-tab"/);
assert.match(index, /id="auth-signup-tab"/);
assert.match(index, /data-auth-signout/);
assert.match(index, /data-map-upload/);
assert.match(index, /data-map-repository/);
assert.match(index, /id="map-repository-overlay"[^>]*repository-overlay/);
assert.match(index, /id="map-repository-search"/);
assert.match(index, /id="map-repository-list"/);
assert.match(index, /id="map-repository-mine-tab"[^>]*aria-selected="true"/);
assert.match(index, /id="map-repository-others-tab"[^>]*aria-selected="false"/);
assert.match(index, /id="auth-account-controls"[^>]*auth-account-controls/);
assert.match(index, /id="auth-account-controls"[\s\S]*data-map-upload[\s\S]*data-auth-signout/);
assert.match(index, /class="auth-role-badge" data-auth-role>User<\/span>/);
assert.match(index, /id="top-settings-bar"[\s\S]*id="auth-account-controls"/);
assert.doesNotMatch(index, /class="toolbar-upload"/);
assert.match(index, /id="map_author"[^>]*readonly/);
assert.match(index, /id="map_category"[^>]*value="maps"[^>]*readonly/);
assert.match(index, /id="map_version"[^>]*value="1"[^>]*readonly/);
assert.doesNotMatch(index, /id="map_axes_forced"/);
assert.match(index, /id="map_dtd"[^>]*role="combobox"[^>]*aria-controls="map-dtd-options"/);
assert.strictEqual((index.match(/data-dtd-value=/g) || []).length, 8);
assert.match(index, /id="map-dtd-options"[^>]*role="listbox"/);
assert.match(index, /src="\.\/js\/localDraft\.js"/);
assert.match(index, /<script type="module" src="\.\/js\/auth\.js"><\/script>/);

assert.match(authSource, /projectId:\s*"tronnerrepository"/);
assert.match(authSource, /onAuthStateChanged\(auth/);
assert.match(authSource, /createUserWithEmailAndPassword\(auth/);
assert.match(authSource, /signInWithEmailAndPassword\(auth/);
assert.match(authSource, /sendPasswordResetEmail\(auth/);
assert.match(authSource, /signOut\(auth\)/);
assert.match(authSource, /browserLocalPersistence/);
assert.match(authSource, /browserSessionPersistence/);
assert.match(authSource, /authSdk\.getIdTokenResult\(user, true\)/);
assert.match(authSource, /claims\.admin === true \? "admin" : claims\.role/);
assert.match(authSource, /currentUserRole === "admin"/);
assert.match(authSource, /repositoryMapIsMine\(map\) \|\| currentUserIsAdmin\(\)/);
assert.match(authSource, /firebase-storage\.js/);
assert.match(authSource, /uploadString\(mapRef, map\.xml/);
assert.match(authSource, /storageSdk\.listAll\(folderReference\)/);
assert.match(authSource, /storageSdk\.getMetadata\(storageSdk\.ref\(storage, map\.fullPath\)\)/);
assert.match(authSource, /authSdk\.getIdToken\(auth\.currentUser\)/);
assert.match(authSource, /Authorization:\s*`Firebase \$\{idToken\}`/);
assert.doesNotMatch(authSource, /getDownloadURL/);
assert.match(authSource, /`\$\{editing \? "Edit" : "Remix"\} \$\{map\.name\} by \$\{map\.author\}`/);
assert.match(authSource, /dataset\.repositoryOpen = map\.fullPath/);
assert.match(authSource, /dataset\.repositoryAction = action/);
assert.match(authSource, /if\(repositoryMapCanEdit\(map\)\) addAction\("edit"\)/);
assert.match(authSource, /if\(!repositoryMapIsMine\(map\) \|\| currentUserIsAdmin\(\)\) addAction\("remix"\)/);
assert.match(authSource, /requestedAction === "edit" && repositoryMapCanEdit\(map\)/);
assert.match(authSource, /repositoryExpandedAuthors = new Set\(\)/);
assert.match(authSource, /heading\.dataset\.repositoryAuthor = author/);
assert.match(authSource, /mapList\.hidden = !expanded/);
assert.match(authSource, /repositoryExpandedAuthors\.clear\(\)/);
assert.match(authSource, /repositoryTab = "mine"/);
assert.match(authSource, /window\.xml_appendRemixSource/);
assert.match(authSource, /depth === 1 \? "_r" : `_r\$\{depth\}`/);
assert.match(authSource, /nameInput\.readOnly = true/);
assert.match(authSource, /function bumpMapVersion\(value\)/);
assert.match(authSource, /function nextAvailableMapVersion\(/);
assert.match(authSource, /storageSdk\.deleteObject\(storageSdk\.ref\(storage, editState\.sourcePath\)\)/);
assert.match(authSource, /const archivePath = `\$\{author\}\/\$\{editState\.sourceCategory\}\/archive\/\$\{sourceFileName\}`/);
assert.match(authSource, /label\.textContent = repositoryEditState \? "Submit edit" : "Upload"/);
assert.match(authSource, /window\.vectron_getRepositoryEditState/);
assert.match(authSource, /targetAuthor: map\.author/);
assert.match(authSource, /sourceOwnerUid/);
assert.match(authSource, /window\.xml_author = author/);
assert.match(authSource, /window\.xml_category = MAP_CATEGORY/);
assert.match(authSource, /vectron_localDraftSetUser\(user\.uid\)/);
assert.match(authSource, /vectron_localDraftSaveNow/);
assert.match(authSource, /setEditorInert\(true\)/);
assert.doesNotMatch(authSource, /[?&](?:skip|bypass|noauth)=/i);

assert.match(vectronSource, /function vectron_start\(\)/);
assert.match(vectronSource, /if\(vectron_started\) return;/);
assert.match(vectronSource, /vectron_localDraftRestore\(\)/);
assert.doesNotMatch(vectronSource, /window\.onload\s*=\s*function\s*\(\)\s*\{\s*vectron_init/);

assert.doesNotMatch(aamapSource + eventSource + xmlSource, /map_axes_forced/);
assert.match(aamapSource, /xml \+= '        <Axes number="'\+axes\+'"\/>'/);
assert.match(eventSource, /mapSettingsCustomCfg\.push\("ARENA_AXES " \+ mapAxes\)/);
assert.match(eventSource, /eventHandler_initDtdCombobox/);
assert.match(xmlSource, /Vectron remix provenance \(oldest source first\)/);
assert.match(xmlSource, /Original map:/);
assert.match(xmlSource, /xml_appendRemixSource/);

assert.match(localDraftSource, /vectron\.localDraft\.v1\./);
assert.match(localDraftSource, /localStorage\.setItem/);
assert.match(localDraftSource, /localStorage\.getItem/);
assert.match(localDraftSource, /beforeunload/);
assert.match(localDraftSource, /visibilitychange/);

assert.match(authCss, /#auth-gate\s*\{[^}]*z-index:\s*20000/s);
assert.match(authCss, /#auth-gate\s*\{[^}]*align-items:\s*center[^}]*justify-items:\s*center/s);
assert.match(authCss, /#auth-gate\s*\{[^}]*background:\s*rgba\(0,\s*0,\s*0,\s*0\.48\)/s);
assert.match(authCss, /\.auth-account-controls\s*\{[^}]*position:\s*static[^}]*margin-left:\s*auto/s);
assert.match(authCss, /\.auth-account-controls\s*\{[^}]*border:\s*0[^}]*background:\s*transparent[^}]*box-shadow:\s*none/s);
assert.match(authCss, /--auth-cyan:\s*#55f4dc/);
assert.match(authCss, /--auth-violet:\s*#9a7cff/);
assert.match(authCss, /\.auth-role-badge\[data-role="admin"\]/);
assert.doesNotMatch(authCss, /#(?:3b94de|1c70bb|68d6e8|398dcc|1c5f96)/i);
assert.doesNotMatch(index, /auth-backdrop|auth-orbit|auth-horizon/);
assert.match(authCss, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(authCss, /@media \(max-width: 720px\)/);
assert.match(authCss, /\.repository-tabs/);
assert.match(authCss, /button\.repository-author-heading/);
assert.match(authCss, /\.repository-author-heading\[aria-expanded="true"\]/);
assert.match(vectronCss, /\.tsb-combobox-menu/);
assert.match(darkCss, /\.tsb-combobox-menu/);

assert.match(storageRules, /match \/\{author\}\/\{category\}\/archive\/\{fileName\}/);
assert.match(storageRules, /match \/\{author\}\/\{category\}\/\{fileName\}/);
assert.match(storageRules, /allow list: if request\.auth != null/);
assert.match(storageRules, /allow get: if request\.auth != null[\s\S]*resource\.name\.matches\('\.\*\\\\\.aamap\\\\\.xml'\)/);
assert.match(storageRules, /request\.auth\.token\.name == author/);
assert.match(storageRules, /request\.resource\.metadata\.ownerUid == request\.auth\.uid/);
assert.match(storageRules, /fileName == request\.resource\.metadata\.mapName \+ '-'/);
assert.match(storageRules, /request\.resource\.metadata\.mapVersion\.matches\('\[0-9\]\+\(\\\\\.\[0-9\]\+\)\*'\)/);
assert.match(storageRules, /request\.resource\.metadata\.mapName ==[\s\S]*request\.resource\.metadata\.remixOriginalName \+ '_r'/);
assert.match(storageRules, /request\.resource\.metadata\.remixOriginalName \+ '_r'[\s\S]*request\.resource\.metadata\.remixDepth/);
assert.match(storageRules, /request\.resource\.metadata\.editSourceVersion != request\.resource\.metadata\.mapVersion/);
assert.match(storageRules, /request\.auth\.token\.admin == true/);
assert.match(storageRules, /isAdmin\(\)[\s\S]*request\.auth\.token\.name == author/);
assert.match(authSource, /editorUid: user\.uid/);
assert.match(authSource, /editorRole: currentUserRole/);
assert.match(storageRules, /request\.resource\.metadata\.archived == 'true'/);
assert.strictEqual((storageRules.match(/return resource == null/g) || []).length, 2);
assert.doesNotMatch(storageRules, /allow update:/);
assert.doesNotMatch(storageRules, /allow (?:read|write): if true/);

console.log("Vectron authentication configuration tests passed.");
